import logging
from dataclasses import dataclass
from typing import Any

import requests
from django.conf import settings
from django.db import transaction
from rest_framework import status
from rest_framework.exceptions import APIException

from apps.survey.choices import (
    ChatbotModelChoices,
    SurveyRoleChoices,
    SurveyStatusChoices,
)
from apps.survey.models import SurveyChatbotMessage, SurveyChatbotSession
from apps.survey.prompts.survey_chatbot_prompt import SURVEY_CHATBOT_PROMPT


class SurveyQuestionGenerationUnavailable(APIException):
    status_code = status.HTTP_503_SERVICE_UNAVAILABLE
    default_detail = "설문 첫 질문을 생성하지 못했습니다. 잠시 후 다시 시도해주세요."
    default_code = "survey_question_generation_unavailable"


@dataclass(frozen=True)
class SurveyChatbotSessionCreateResult:
    session_id: str
    status: str
    ai_question: str
    progress: dict
    recommendation_ready: bool = False

    def as_dict(self) -> dict:
        return {
            "session_id": self.session_id,
            "status": self.status,
            "ai_question": self.ai_question,
            "progress": self.progress,
            "recommendation_ready": self.recommendation_ready,
        }


class SurveyChatbotSessionService:
    def create_session(
        self, user: Any, is_reset: bool = False
    ) -> SurveyChatbotSessionCreateResult:
        with transaction.atomic():
            if is_reset:
                self.delete_user_session(user)

            session, created = self.get_or_create_user_session(user)

            if self.should_initialize_session(session, created):
                self.initialize_session(session)

            question = self.get_current_question(session)

        return SurveyChatbotSessionCreateResult(
            session_id=str(session.id),
            status=session.status,
            ai_question=question,
            progress=self.build_progress(session),
        )

    def get_or_create_user_session(
        self, user: Any
    ) -> tuple[SurveyChatbotSession, bool]:
        return SurveyChatbotSession.objects.select_for_update().get_or_create(
            user=user,
            defaults={
                "using_model": ChatbotModelChoices.GEMINI_2_5_FLASH,
                "status": SurveyStatusChoices.OPEN,
            },
        )

    def delete_user_session(self, user: Any) -> None:
        SurveyChatbotSession.objects.select_for_update().filter(user=user).delete()

    def should_initialize_session(
        self,
        session: SurveyChatbotSession,
        created: bool,
    ) -> bool:
        return (
            created
            or session.status == SurveyStatusChoices.CLOSED
            or not session.messages.exists()
        )

    def initialize_session(self, session: SurveyChatbotSession) -> None:
        self.clear_session(session)
        session.status = SurveyStatusChoices.OPEN
        session.target_question_count = None
        session.using_model = ChatbotModelChoices.GEMINI_2_5_FLASH
        session.save(update_fields=["status", "target_question_count", "using_model"])

        SurveyChatbotMessage.objects.create(
            session=session,
            message=self.generate_first_question(),
            role=SurveyRoleChoices.AI,
            sequence=1,
        )

    def clear_session(self, session: SurveyChatbotSession) -> None:
        session.messages.all().delete()
        if hasattr(session, "results"):
            session.results.delete()

    def get_current_question(self, session: SurveyChatbotSession) -> str:
        message = (
            session.messages.filter(role=SurveyRoleChoices.AI)
            .order_by("-sequence")
            .first()
        )
        return message.message if message else self.generate_first_question()

    def build_progress(self, session: SurveyChatbotSession) -> dict:
        current_step = session.messages.filter(role=SurveyRoleChoices.USER).count()
        total_steps = session.target_question_count
        completion_rate = round(current_step / total_steps, 2) if total_steps else None

        return {
            "current_step": current_step,
            "total_steps": total_steps,
            "completion_rate": completion_rate,
        }

    def generate_first_question(self) -> str:
        prompt = self.load_first_question_prompt()
        question = self.generate_question_with_llm(prompt)
        if question and self.is_complete_first_question(question):
            return question
        logging.getLogger(__name__).warning(
            "Invalid survey question generated by LLM: %s", question
        )
        raise SurveyQuestionGenerationUnavailable()

    def generate_question_with_llm(self, prompt: str) -> str | None:
        api_key = settings.SURVEY_CHATBOT_GEMINI_API_KEY
        if not api_key:
            return None

        url = (
            f"{settings.SURVEY_CHATBOT_GEMINI_BASE_URL}/v1beta/models/"
            f"{settings.SURVEY_CHATBOT_GEMINI_MODEL}:generateContent"
        )
        payload = {
            "contents": [
                {
                    "role": "user",
                    "parts": [{"text": prompt}],
                }
            ],
            "generationConfig": {
                "temperature": 0.4,
                "maxOutputTokens": 1024,
                "responseMimeType": "text/plain",
            },
        }
        try:
            response = requests.post(
                url,
                params={"key": api_key},
                json=payload,
                timeout=settings.SURVEY_CHATBOT_GEMINI_TIMEOUT,
            )
            response.raise_for_status()
        except requests.RequestException:
            logging.getLogger(__name__).exception(
                "Failed to generate survey chatbot question."
            )
            return None

        response_data = response.json()
        question = self.extract_text_from_gemini_response(response_data)
        if not question:
            logging.getLogger(__name__).warning(
                "Empty Gemini response for survey question: %s", response_data
            )
        return question

    def extract_text_from_gemini_response(self, data: dict) -> str | None:
        try:
            parts = data["candidates"][0]["content"]["parts"]
        except KeyError, IndexError, TypeError:
            return None

        text = "".join(part.get("text", "") for part in parts if isinstance(part, dict))
        text = text.strip()
        return text or None

    def is_complete_first_question(self, question: str | None) -> bool:
        if not question:
            return False

        question = question.strip()
        return len(question) >= 30 and question.endswith(
            ("요?", "나요?", "까요?", "주세요.")
        )

    def load_first_question_prompt(self) -> str:
        return SURVEY_CHATBOT_PROMPT.strip()
