# Generated by Django 6.0.4 on 2026-04-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameExclusion",
            fields=[
                (
                    "game_exclusion_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("game_id", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=30)),
                ("reason", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "game_exclusions",
            },
        ),
        migrations.CreateModel(
            name="GameLikeCount",
            fields=[
                (
                    "game_like_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("game_id", models.IntegerField(unique=True)),
                ("like_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "game_like_counts",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("like_count__gte", 0)),
                        name="ck_game_like_counts_non_negative",
                    )
                ],
            },
        ),
    ]
