# Generated by Django 6.0.4 on 2026-04-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "game_id",
                    models.BigIntegerField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="IGDB_게임_고유_ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="게임 이름")),
                ("slug", models.CharField(max_length=255, verbose_name="슬러그")),
                (
                    "summary",
                    models.TextField(blank=True, null=True, verbose_name="게임 개요"),
                ),
                (
                    "storyline",
                    models.TextField(
                        blank=True, null=True, verbose_name="게임 스토리라인"
                    ),
                ),
                (
                    "category",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="게임 카테고리"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="게임 출시 상태"
                    ),
                ),
                (
                    "first_release_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="게임 출시일"
                    ),
                ),
                (
                    "franchises",
                    models.JSONField(
                        blank=True, null=True, verbose_name="프랜차이즈 정보"
                    ),
                ),
                (
                    "version_title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="버전 명"
                    ),
                ),
                (
                    "remakes",
                    models.JSONField(
                        blank=True, null=True, verbose_name="리메이크 정보"
                    ),
                ),
                (
                    "remasters",
                    models.JSONField(
                        blank=True, null=True, verbose_name="리마스터 정보"
                    ),
                ),
                (
                    "expansions",
                    models.JSONField(blank=True, null=True, verbose_name="확장팩 목록"),
                ),
                (
                    "dlcs",
                    models.JSONField(blank=True, null=True, verbose_name="DLC 목록"),
                ),
                (
                    "language_supports",
                    models.JSONField(blank=True, null=True, verbose_name="지원 언어"),
                ),
                (
                    "rating",
                    models.FloatField(blank=True, null=True, verbose_name="IGDB 평점"),
                ),
                (
                    "rating_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="유저 평가 수"
                    ),
                ),
                (
                    "aggregated_rating",
                    models.FloatField(
                        blank=True, null=True, verbose_name="전문가 평점"
                    ),
                ),
                (
                    "aggregated_rating_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="전문가 평가 수"
                    ),
                ),
                (
                    "total_rating",
                    models.FloatField(blank=True, null=True, verbose_name="통합 평점"),
                ),
                (
                    "total_rating_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="통합 평가 수"
                    ),
                ),
                (
                    "follows",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="팔로우 수"
                    ),
                ),
                (
                    "hypes",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="기대 지수"
                    ),
                ),
                (
                    "game_modes",
                    models.JSONField(blank=True, null=True, verbose_name="게임 모드"),
                ),
                (
                    "player_perspectives",
                    models.JSONField(
                        blank=True, null=True, verbose_name="플레이어 시점"
                    ),
                ),
                (
                    "themes",
                    models.JSONField(blank=True, null=True, verbose_name="게임 테마"),
                ),
                (
                    "genres",
                    models.JSONField(blank=True, null=True, verbose_name="게임 장르"),
                ),
                (
                    "keywords",
                    models.JSONField(blank=True, null=True, verbose_name="게임 키워드"),
                ),
                (
                    "multiplayer_modes",
                    models.JSONField(
                        blank=True, null=True, verbose_name="멀티플레이 모드"
                    ),
                ),
                (
                    "screenshots",
                    models.JSONField(blank=True, null=True, verbose_name="스크린샷"),
                ),
                (
                    "videos",
                    models.JSONField(
                        blank=True, null=True, verbose_name="트레일러 영상"
                    ),
                ),
                (
                    "websites",
                    models.JSONField(blank=True, null=True, verbose_name="게임 주소"),
                ),
                (
                    "involved_companies",
                    models.JSONField(
                        blank=True, null=True, verbose_name="관련 기업 정보"
                    ),
                ),
                (
                    "collection",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="게임 시리즈"
                    ),
                ),
                (
                    "parent_game",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="게임 확장팩"
                    ),
                ),
                (
                    "cover",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="커버 이미지"
                    ),
                ),
                (
                    "game_type",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="게임 유형"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "like_count",
                    models.IntegerField(default=0, verbose_name="좋아요 수"),
                ),
                (
                    "is_ban",
                    models.BooleanField(default=False, verbose_name="블랙리스트"),
                ),
            ],
            options={
                "verbose_name": "게임 저장 테이블",
                "db_table": "game_list",
            },
        ),
        migrations.DeleteModel(
            name="GameExclusion",
        ),
        migrations.DeleteModel(
            name="GameLikeCount",
        ),
        migrations.RemoveConstraint(
            model_name="usergamelike",
            name="user_game_likes_unique",
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["status", "game_type", "-first_release_date", "-game_id"],
                name="idx_game_match_active",
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["-first_release_date", "-game_id"], name="idx_game_release_desc"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["-rating", "-rating_count", "-game_id"],
                name="idx_game_rating_desc",
            ),
        ),
        migrations.DeleteModel(
            name="UserGamelike",
        ),
    ]
