# Generated by Django 6.0.4 on 2026-04-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_game_delete_gameexclusion_delete_gamelikecount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="platforms",
            field=models.JSONField(blank=True, null=True, verbose_name="지원 플랫폼"),
        ),
    ]
