# Generated by Django 6.0.4 on 2026-04-30 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_game_name_ko"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameBlacklist",
            fields=[],
            options={
                "verbose_name": "게임 블랙리스트",
                "verbose_name_plural": "게임 블랙리스트",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("games.game",),
        ),
        migrations.AlterModelOptions(
            name="game",
            options={
                "verbose_name": "게임 저장 테이블",
                "verbose_name_plural": "게임 저장 테이블",
            },
        ),
    ]
