services:
  django:
    container_name: pgti_django
    env_file:
      - envs/.env.prod
    build:
      context: .
    working_dir: /oz_union_16_BE
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --workers 3 --bind 0.0.0.0:8000 config.wsgi:application"
    expose:
      - "8000"
    volumes:
      - .:/oz_union_16_BE
      - static_volume:/oz_union_16_BE/static
      - media_volume:/oz_union_16_BE/media
    networks:
      - ws
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  nginx:
    image: nginx:latest
    container_name: pgti_nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/oz_union_16_BE/static
      - media_volume:/oz_union_16_BE/media
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    networks:
      - ws

  db:
    image: postgres:14
    container_name: pgti_postgres
    env_file:
      - envs/.env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ws
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  redis:
    image: redis:latest
    container_name: pgti_redis
    networks:
      - ws
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

networks:
  ws:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  postgres_data: