services:
  django:
    container_name: pgti_django
    image: [DOCKER_USERNAME]/[DOCKER_REPO]:django-prod
    env_file:
      - envs/.env.prod
    working_dir: /oz_union_16_BE
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --workers 3 --bind 0.0.0.0:8000 config.wsgi:application"
    expose:
      - "8000"
    volumes:
      - static_volume:/oz_union_16_BE/static
      - media_volume:/oz_union_16_BE/media
    networks:
      - ws
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  nginx:
    image: [DOCKER_USERNAME]/[DOCKER_REPO]:nginx-prod
    container_name: pgti_nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
    volumes:
      - static_volume:/oz_union_16_BE/static
      - media_volume:/oz_union_16_BE/media
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    networks:
      - ws

  db:
    image: pgvector/pgvector:pg14
    container_name: pgti_postgres
    env_file:
      - envs/.env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ws
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: pgti_redis
    networks:
      - ws
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  ws:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume: