# Generated by Django 6.0.4 on 2026-04-10 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatbotSession",
            fields=[
                (
                    "chatbot_sessions_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "using_model",
                    models.CharField(
                        choices=[("GEMINI_2.5", "Gemini 2.5")], max_length=30
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "ACTIVE"),
                            ("CLOSED", "CLOSED"),
                            ("EXPIRED", "EXPIRED"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "chatbot_sessions",
            },
        ),
        migrations.CreateModel(
            name="ChatbotMessage",
            fields=[
                (
                    "chatbot_completions_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("USER", "USER"),
                            ("ASSISTANT", "ASSISTANT"),
                            ("SYSTEM", "SYSTEM"),
                        ],
                        max_length=10,
                    ),
                ),
                ("sequence", models.IntegerField()),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chatbot_session",
                    models.ForeignKey(
                        db_column="chatbot_sessions_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chatbot.chatbotsession",
                    ),
                ),
            ],
            options={
                "db_table": "chatbot_messages",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chatbot_session", "sequence"),
                        name="uq_chatbot_messages_session_sequence",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sequence__gte", 1)),
                        name="ck_chatbot_messages_sequence_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("message", ""), _negated=True),
                        name="ck_chatbot_messages_not_empty",
                    ),
                ],
            },
        ),
    ]
