# Generated by Django 6.0.4 on 2026-04-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbotsession",
            name="pending_question",
            field=models.TextField(blank=True, null=True),
        ),
    ]
