# Generated by Django 6.0.4 on 2026-04-10 02:49

import apps.users.models
import django.db.models.deletion
import pgvector.django.vector
from pgvector.django import VectorExtension
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("user_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "login_id",
                    models.CharField(db_index=True, max_length=30, unique=True),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "password",
                    models.CharField(db_column="hashed_password", max_length=128),
                ),
                ("name", models.CharField(max_length=30)),
                ("nickname", models.CharField(max_length=10)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "gender",
                    models.CharField(choices=[("M", "M"), ("W", "W")], max_length=1),
                ),
                ("birthday", models.DateField()),
                (
                    "profile_img_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
            managers=[
                ("objects", apps.users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "user_preferences_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "survey_vector",
                    pgvector.django.vector.VectorField(blank=True, null=True),
                ),
                (
                    "match_vector",
                    pgvector.django.vector.VectorField(blank=True, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_preferences",
            },
        ),
        migrations.CreateModel(
            name="SocialUser",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("provider", models.CharField(max_length=20)),
                ("provider_id", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "social_users",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "provider_id"),
                        name="uq_social_provider_provider_id",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserLikeBookmark",
            fields=[
                (
                    "user_game_like_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("game_id", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="like_bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_like_bookmarks",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "game_id"), name="uq_user_game_bookmark"
                    )
                ],
            },
        ),
    ]
