# Generated by Django 6.0.4 on 2026-04-20 02:49

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreference",
            name="match_vector",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=14, null=True, verbose_name="매치 벡터"
            ),
        ),
    ]
