# Generated by Django 6.0.4 on 2026-04-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_userpreference_match_vector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialuser",
            name="provider",
            field=models.CharField(
                choices=[("kakao", "Kakao"), ("naver", "Naver"), ("google", "Google")],
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "active"), ("SUSPENDED", "suspended")],
                default="ACTIVE",
                max_length=10,
            ),
        ),
    ]
