# Generated by Django 6.0.4 on 2026-04-27 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_socialuser_provider_alter_user_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferenceDashboard",
            fields=[],
            options={
                "verbose_name": "사용자 특성 데이터",
                "verbose_name_plural": "사용자 특성 데이터",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.userpreference",),
        ),
    ]
