# Generated by Django 6.0.4 on 2026-04-27 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_game_delete_gameexclusion_delete_gamelikecount_and_more"),
        ("users", "0003_alter_socialuser_provider_alter_user_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferenceDashboard",
            fields=[],
            options={
                "verbose_name": "사용자 특성 데이터",
                "verbose_name_plural": "사용자 특성 데이터",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.userpreference",),
        ),
        migrations.RemoveConstraint(
            model_name="userlikebookmark",
            name="uq_user_game_bookmark",
        ),
        migrations.RenameField(
            model_name="userlikebookmark",
            old_name="game_id",
            new_name="game",
        ),
        migrations.AlterField(
            model_name="userlikebookmark",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liked_by_users",
                to="games.game",
            ),
        ),
        migrations.AlterField(
            model_name="userlikebookmark",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="like_bookmarks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="userlikebookmark",
            constraint=models.UniqueConstraint(
                fields=("user", "game"), name="unique_user_game_like"
            ),
        ),
    ]
