events {
    worker_connections 1024;
}

http {
    upstream django_server {
        # 여기서 'web'은 docker-compose의 django 서비스 이름이어야 합니다.
        # 만약 서비스명이 'pgti_django'라면 아래를 pgti_django:8000으로 바꾸세요.
        server pgti_django:8000;
    }

    server {
        listen 80;
        server_name nginx;

        location / {
            proxy_pass http://django_server;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /static/ {
            alias /PGTI/static/;
        }
    }
}