"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 로그로 경로를 확인해보는 코드를 임시로 넣어보세요 (디버깅용)
print(f"DEBUG: BASE_DIR is {BASE_DIR}")
print(f"DEBUG: STATIC_ROOT is {os.path.join(BASE_DIR, 'static')}")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    raise ValueError("DJANGO_SECRET_KEY environment variable not set")

# SECURITY WARNING: don't run with debug turned on in production!


# Application definition
DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
]

THIRD_PARTY_APPS = [
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "rest_framework",
    "corsheaders",
    "drf_spectacular",
    "pgvector",
]

CUSTOM_APPS: list[str] = [
    "apps.chatbot",
    "apps.games",
    "apps.match",
    "apps.survey",
    "apps.users",
    "apps.core",
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + CUSTOM_APPS

AUTH_USER_MODEL = "users.User"

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",  # 이 줄이 반드시 있어야 합니다!
        "NAME": os.environ.get("DB_NAME", "oz_combined_PGTI"),
        "USER": os.environ.get("DB_USER", "postgres"),
        "PASSWORD": os.environ.get("DB_PASSWORD", "pgti1234"),
        "HOST": os.environ.get("DB_HOST", "db"),  # DB_HOST 변수 사용
        "PORT": os.environ.get("DB_PORT", "5432"),  # DB_PORT 변수 사용
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "EXCEPTION_HANDLER": "apps.core.exceptions.custom_exception_handler",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=180),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
}


SPECTACULAR_SETTINGS = {
    "TITLE": "PGTI Backend API",
    "DESCRIPTION": "PGTI 웹 사이트 개발을 위한 API입니다.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SWAGGER_UI_SETTINGS": {
        "dom_id": "#swagger-ui",
        "layout": "BaseLayout",
        "deepLinking": True,
        "persistAuthorization": True,
        "displayOperationId": True,
        "filter": True,
    },
    "SERVE_PERMISSIONS": ["rest_framework.permissions.AllowAny"],
    "SECURITY": [
        {
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            }
        }
    ],
}

# ---------------------------------------------------------------------------
# CORS 공통 설정
# ---------------------------------------------------------------------------

CORS_ALLOW_CREDENTIALS = True

# 허용할 HTTP 메서드
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

# 허용할 요청 헤더
CORS_ALLOW_HEADERS = [
    "accept",
    "authorization",
    "content-type",
    "origin",
    "x-csrftoken",
    "x-requested-with",
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# IGDB API Settings
IGDB_ID = os.getenv("IGDB_CLIENT_ID")
IGDB_ACCESS_TOKEN = os.getenv("IGDB_ACCESS_TOKEN")
IGDB_BASE_URL = os.getenv("IGDB_BASE_URL", "https://api.igdb.com/v4/games")
IGDB_TIMEOUT_SEC = int(os.getenv("IGDB_TIMEOUT_SEC", "10"))

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    }
}

MATCH_GENRE_IMAGE_CACHE_KEY = os.getenv(
    "MATCH_GENRE_IMAGE_CACHE_KEY",
    "match:genre:image_map:v1",
)
MATCH_REDIS_URL = os.getenv("MATCH_REDIS_URL", "redis://redis:6379/0")
# 장르 이미지 조회 API용(짧게)
MATCH_GENRE_IMAGE_QUERY_TIMEOUT = int(os.getenv("MATCH_GENRE_IMAGE_QUERY_TIMEOUT", "2"))
# 장르 이미지 배치용(길게)
MATCH_GENRE_IMAGE_BATCH_TIMEOUT = int(
    os.getenv("MATCH_GENRE_IMAGE_BATCH_TIMEOUT", "15")
)

KAKAO_CLIENT_ID      = os.getenv("KAKAO_CLIENT_ID")
KAKAO_CLIENT_SECRET  = os.getenv("KAKAO_CLIENT_SECRET")
KAKAO_REDIRECT_URI   = os.getenv("KAKAO_REDIRECT_URI")
KAKAO_LOCAL_REDIRECT_URI   = os.getenv("KAKAO_LOCAL_REDIRECT_URI")


NAVER_CLIENT_ID      = os.getenv("NAVER_CLIENT_ID")
NAVER_CLIENT_SECRET  = os.getenv("NAVER_CLIENT_SECRET")
NAVER_REDIRECT_URI   =  os.getenv("NAVER_REDIRECT_URI")
NAVER_LOCAL_REDIRECT_URI   =  os.getenv("NAVER_LOCAL_REDIRECT_URI")


GOOGLE_CLIENT_ID     = os.getenv("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")
GOOGLE_REDIRECT_URI  = os.getenv("GOOGLE_REDIRECT_URI")
GOOGLE_LOCAL_REDIRECT_URI  = os.getenv("GOOGLE_LOCAL_REDIRECT_URI")

FRONTEND_CALLBACK_URI = os.getenv("FRONTEND_CALLBACK_URI")
FRONTEND_LOCAL_CALLBACK_URI = os.getenv("FRONTEND_LOCAL_CALLBACK_URI")

