SURVEY_RECOMMENDATION_DEFAULT_PAGE_SIZE = 5
SURVEY_RECOMMENDATION_MAX_PAGE_SIZE = 15
SURVEY_RECOMMENDATION_REQUIRED_PLATFORM_ID = 6
SURVEY_RECOMMENDATION_MIN_RELEASE_YEAR = 2000

SURVEY_ALLOWED_GAME_CATEGORIES: tuple[int, ...] = (0, 8, 9)
SURVEY_REQUIRED_RELEASE_STATUS: int = 0
