# Generated by Django 6.0.4 on 2026-04-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MatchResult",
            fields=[
                (
                    "match_results_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("game_id", models.IntegerField(db_index=True)),
                ("rating", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "match_results",
            },
        ),
    ]
