# Generated by Django 6.0.4 on 2026-04-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MatchResult",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "match_results_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("game_id", models.IntegerField(db_index=True)),
                ("rating", models.PositiveSmallIntegerField()),
            ],
            options={
                "db_table": "match_results",
            },
        ),
    ]
