# Generated by Django 6.0.4 on 2026-04-16 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("match", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="matchresult",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_results",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="matchresult",
            constraint=models.UniqueConstraint(
                fields=("user", "game_id"), name="uq_match_results_user_game"
            ),
        ),
        migrations.AddConstraint(
            model_name="matchresult",
            constraint=models.CheckConstraint(
                condition=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                name="ck_match_results_rating_1_5",
            ),
        ),
    ]
