# Generated by Django 6.0.4 on 2026-04-16 14:48

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchGameGenreMap",
            fields=[
                (
                    "match_game_genre_map_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("game_id", models.IntegerField(db_index=True)),
                ("igdb_genre_id", models.IntegerField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "match_game_genre_map",
            },
        ),
        migrations.CreateModel(
            name="MatchGamePreference",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "match_game_preference_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("game_id", models.IntegerField(db_index=True)),
                ("genre_id", models.IntegerField(db_index=True)),
                (
                    "game_preference_vector",
                    pgvector.django.vector.VectorField(dimensions=14),
                ),
            ],
            options={
                "db_table": "match_game_preference",
            },
        ),
        migrations.CreateModel(
            name="MatchGameRating",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "match_game_rating_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("star_rating", models.PositiveSmallIntegerField()),
                (
                    "effective_rating",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                ("rating_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "match_game_ratings",
            },
        ),
        migrations.RemoveConstraint(
            model_name="matchresult",
            name="uq_match_results_user_game",
        ),
        migrations.RemoveConstraint(
            model_name="matchresult",
            name="ck_match_results_rating_1_5",
        ),
        migrations.AddConstraint(
            model_name="matchgamegenremap",
            constraint=models.UniqueConstraint(
                fields=("game_id", "igdb_genre_id"),
                name="uq_match_game_genre_map_game_genre",
            ),
        ),
        migrations.AddIndex(
            model_name="matchgamepreference",
            index=models.Index(
                fields=["genre_id"], name="idx_match_game_preference_genre_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="matchgamepreference",
            constraint=models.UniqueConstraint(
                fields=("game_id",), name="uq_match_game_preference_game_id"
            ),
        ),
        migrations.AddField(
            model_name="matchgamerating",
            name="match_game_preference",
            field=models.ForeignKey(
                db_column="match_game_preference_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="match.matchgamepreference",
            ),
        ),
        migrations.AddField(
            model_name="matchgamerating",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_game_ratings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="matchresult",
            name="user",
        ),
        migrations.AddConstraint(
            model_name="matchgamerating",
            constraint=models.UniqueConstraint(
                fields=("user", "match_game_preference"),
                name="uq_match_game_ratings_user_preference",
            ),
        ),
        migrations.AddConstraint(
            model_name="matchgamerating",
            constraint=models.CheckConstraint(
                condition=models.Q(("star_rating__gte", 1), ("star_rating__lte", 5)),
                name="ck_match_game_ratings_star_rating_1_5",
            ),
        ),
        migrations.DeleteModel(
            name="MatchResult",
        ),
    ]
