# Generated by Django 6.0.4 on 2026-04-24 03:32

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_game_delete_gameexclusion_delete_gamelikecount_and_more"),
        ("match", "0003_matchgamegenremap_matchgamepreference_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="matchgamegenremap",
            name="uq_match_game_genre_map_game_genre",
        ),
        migrations.RemoveConstraint(
            model_name="matchgamepreference",
            name="uq_match_game_preference_game_id",
        ),
        migrations.RemoveConstraint(
            model_name="matchgamerating",
            name="uq_match_game_ratings_user_preference",
        ),
        migrations.RemoveConstraint(
            model_name="matchgamerating",
            name="ck_match_game_ratings_star_rating_1_5",
        ),
        migrations.RemoveIndex(
            model_name="matchgamepreference",
            name="idx_mgp_genre_id",
        ),
        migrations.AddField(
            model_name="matchgamegenremap",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일"),
        ),
        migrations.AddField(
            model_name="matchgamerating",
            name="game",
            field=models.ForeignKey(
                blank=True,
                db_column="game_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_ratings",
                to="games.game",
            ),
        ),
        migrations.AlterField(
            model_name="matchgamegenremap",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
        ),
        migrations.AlterField(
            model_name="matchgamegenremap",
            name="game_id",
            field=models.ForeignKey(
                db_column="game_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="genre_maps",
                to="games.game",
            ),
        ),
        migrations.AlterField(
            model_name="matchgamegenremap",
            name="igdb_genre_id",
            field=models.PositiveSmallIntegerField(db_column="igdb_genre_id"),
        ),
        migrations.AlterField(
            model_name="matchgamepreference",
            name="game_id",
            field=models.ForeignKey(
                db_column="game_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_preferences",
                to="games.game",
                verbose_name="게임 ID",
            ),
        ),
        migrations.AlterField(
            model_name="matchgamepreference",
            name="game_preference_vector",
            field=pgvector.django.vector.VectorField(
                dimensions=14, verbose_name="게임 취향 벡터"
            ),
        ),
        migrations.AlterField(
            model_name="matchgamerating",
            name="effective_rating",
            field=models.DecimalField(
                decimal_places=2, max_digits=4, verbose_name="유효 평점"
            ),
        ),
        migrations.AlterField(
            model_name="matchgamerating",
            name="rating_count",
            field=models.IntegerField(default=0, verbose_name="평가 횟수"),
        ),
        migrations.AlterField(
            model_name="matchgamerating",
            name="star_rating",
            field=models.SmallIntegerField(verbose_name="평점"),
        ),
        migrations.AlterField(
            model_name="matchgamerating",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_ratings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="matchgamegenremap",
            index=models.Index(
                fields=["igdb_genre_id", "game_id"], name="idx_mggm_genre_game"
            ),
        ),
        migrations.AddIndex(
            model_name="matchgamepreference",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["game_preference_vector"],
                m=16,
                name="idx_mgp_vector_cosine_hnsw",
                opclasses=["vector_cosine_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="matchgamerating",
            index=models.Index(fields=["game"], name="idx_mgr_game"),
        ),
        migrations.AddConstraint(
            model_name="matchgamegenremap",
            constraint=models.UniqueConstraint(
                fields=("game_id", "igdb_genre_id"), name="uq_mggm_game_genre"
            ),
        ),
        migrations.AddConstraint(
            model_name="matchgamegenremap",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("igdb_genre_id__gte", 1), ("igdb_genre_id__lte", 14)
                ),
                name="ck_mggm_genre_id_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="matchgamepreference",
            constraint=models.UniqueConstraint(fields=("game_id",), name="uq_mgp_game"),
        ),
        migrations.AddConstraint(
            model_name="matchgamerating",
            constraint=models.UniqueConstraint(
                fields=("user", "game"), name="uq_mgr_user_game"
            ),
        ),
        migrations.AddConstraint(
            model_name="matchgamerating",
            constraint=models.CheckConstraint(
                condition=models.Q(("star_rating__gte", 1), ("star_rating__lte", 5)),
                name="ck_mgr_star_rating_range",
            ),
        ),
        migrations.RemoveField(
            model_name="matchgamerating",
            name="match_game_preference",
        ),
        migrations.RemoveField(
            model_name="matchgamepreference",
            name="genre_id",
        ),
    ]
