# Generated by Django 6.0.4 on 2026-04-24 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_game_delete_gameexclusion_delete_gamelikecount_and_more"),
        (
            "match",
            "0004_remove_matchgamegenremap_uq_match_game_genre_map_game_genre_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchgamerating",
            name="game",
            field=models.ForeignKey(
                db_column="game_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_ratings",
                to="games.game",
            ),
        ),
    ]
