# Generated by Django 6.0.4 on 2026-04-28 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0005_alter_matchgamerating_game"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchCandidateRetryState",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "match_candidate_retry_state_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("api_genre_id", models.PositiveSmallIntegerField()),
                ("candidate_date", models.DateField()),
                ("last_completed_retry_no", models.IntegerField(default=-1)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_candidate_retry_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "match_candidate_retry_state",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "api_genre_id", "candidate_date"),
                        name="uq_mcrs_user_genre_date",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("api_genre_id__gte", 1), ("api_genre_id__lte", 8)
                        ),
                        name="ck_mcrs_api_genre_range",
                    ),
                ],
            },
        ),
    ]
