# Generated by Django 6.0.4 on 2026-04-30 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_gameblacklist_alter_game_options"),
        ("match", "0006_matchcandidateretrystate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchGenreImagePublished",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "match_genre_image_published_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("api_genre_id", models.PositiveSmallIntegerField()),
                ("image_url", models.TextField()),
                (
                    "game",
                    models.ForeignKey(
                        db_column="game_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_genre_image_published",
                        to="games.game",
                    ),
                ),
                (
                    "selected_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="selected_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="selected_match_genre_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "match_genre_image_published",
                "indexes": [models.Index(fields=["game"], name="idx_mgip_game")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("api_genre_id",), name="uq_mgip_api_genre"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("api_genre_id__gte", 1), ("api_genre_id__lte", 8)
                        ),
                        name="ck_mgip_api_genre_range",
                    ),
                ],
            },
        ),
    ]
