# Generated by Django 6.0.4 on 2026-04-16 01:36

import uuid

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatbotMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("chatbot", "Ai")],
                        max_length=10,
                        verbose_name="발신 주체",
                    ),
                ),
                ("content", models.TextField(verbose_name="내용")),
            ],
            options={
                "verbose_name": "챗봇 메시지",
                "verbose_name_plural": "챗봇 메시지 목록",
                "db_table": "chatbot_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="GameCache",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        help_text="IGDB 고유 ID", primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("genres", models.TextField()),
                ("description", models.TextField()),
                ("cover_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1536)),
            ],
            options={
                "db_table": "game_cache",
            },
        ),
        migrations.CreateModel(
            name="SurveyChatbotSession",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("activated", "Activated"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=10,
                        verbose_name="세션 상태",
                    ),
                ),
                (
                    "progress_rate",
                    models.CharField(default="0%", max_length=4, verbose_name="진행률"),
                ),
                (
                    "summary_text",
                    models.TextField(blank=True, null=True, verbose_name="취향 요약"),
                ),
            ],
            options={
                "verbose_name": "챗봇 세션",
                "verbose_name_plural": "챗봇 세션 목록",
                "db_table": "chatbot_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Surveyresults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "raw_results_text",
                    models.TextField(
                        blank=True,
                        help_text="LLM이 요약한 자연어 취향 문장을 저장하며, 벡터 생성의 소스로 사용됩니다.",
                        null=True,
                        verbose_name="원본 취향 텍스트",
                    ),
                ),
            ],
            options={
                "verbose_name": "설문 결과 및 취향",
                "verbose_name_plural": "설문 결과 및 취향 목록",
                "db_table": "survey_results",
            },
        ),
    ]
