# Generated by Django 6.0.4 on 2026-04-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SurveyResult",
            fields=[
                (
                    "survey_results_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("survey_answer", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "survey_results",
            },
        ),
    ]
