# Generated by Django 6.0.4 on 2026-04-10 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("survey", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyresult",
            name="user",
            field=models.OneToOneField(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="survey_result",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyresult",
            constraint=models.CheckConstraint(
                condition=models.Q(("survey_answer__gte", 0)),
                name="ck_survey_results_answer_non_negative",
            ),
        ),
    ]
