# Generated by Django 6.0.4 on 2026-04-17 07:49

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyChatbotMessage",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "survey_chatbot_messages_id",
                    models.BigAutoField(
                        db_column="survey_chatbot_messages_id",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        db_column="message", null=True, verbose_name="메시지 내용"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "사용자"), ("chatbot", "챗봇")],
                        db_column="role",
                        max_length=10,
                        null=True,
                        verbose_name="발신 주체",
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        db_column="sequence", null=True, verbose_name="순서"
                    ),
                ),
            ],
            options={
                "verbose_name": "챗봇 메시지",
                "db_table": "survey_chatbot_messages",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="SurveyGameVector",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "survey_game_vector_id",
                    models.BigAutoField(
                        db_column="survey_game_vector_id",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        db_column="embedding", dimensions=1536, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "게임 벡터",
                "db_table": "survey_game_vector",
            },
        ),
        migrations.CreateModel(
            name="SurveyRecommendGameList",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "survey_recommend_game_list_id",
                    models.BigAutoField(
                        db_column="survey_recommend_game_list_id",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "game_id",
                    models.IntegerField(
                        db_column="game_id", null=True, verbose_name="IGDB 게임 ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(db_column="title", max_length=30, null=True),
                ),
                ("genre", models.TextField(db_column="genre", null=True)),
                ("description", models.TextField(db_column="description", null=True)),
                ("cover_url", models.URLField(db_column="cover_url", null=True)),
                (
                    "survey_game_vector",
                    models.ForeignKey(
                        db_column="survey_game_vector_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to="survey.surveygamevector",
                    ),
                ),
            ],
            options={
                "verbose_name": "게임 마스터 정보",
                "db_table": "survey_recommend_game_list",
            },
        ),
        migrations.RemoveField(
            model_name="chatbotmessage",
            name="session",
        ),
        migrations.DeleteModel(
            name="GameCache",
        ),
        migrations.AlterModelOptions(
            name="surveychatbotsession",
            options={"verbose_name": "챗봇 세션"},
        ),
        migrations.AlterModelOptions(
            name="surveyresults",
            options={"verbose_name": "설문 결과"},
        ),
        migrations.RemoveField(
            model_name="surveychatbotsession",
            name="progress_rate",
        ),
        migrations.RemoveField(
            model_name="surveychatbotsession",
            name="status",
        ),
        migrations.RemoveField(
            model_name="surveychatbotsession",
            name="summary_text",
        ),
        migrations.RemoveField(
            model_name="surveychatbotsession",
            name="user",
        ),
        migrations.RemoveField(
            model_name="surveyresults",
            name="id",
        ),
        migrations.RemoveField(
            model_name="surveyresults",
            name="raw_results_text",
        ),
        migrations.AddField(
            model_name="surveyresults",
            name="chatbot_session",
            field=models.ForeignKey(
                blank=True,
                db_column="survey_chatbot_sessions_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="survey.surveychatbotsession",
            ),
        ),
        migrations.AddField(
            model_name="surveyresults",
            name="survey_answer",
            field=models.TextField(
                blank=True,
                db_column="survey_answer",
                null=True,
                verbose_name="유저 답변 요약",
            ),
        ),
        migrations.AddField(
            model_name="surveyresults",
            name="survey_results_id",
            field=models.BigAutoField(
                db_column="survey_results_id", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="surveyresults",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="survey_results",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelTable(
            name="surveychatbotsession",
            table="survey_chatbot_sessions",
        ),
        migrations.AddField(
            model_name="surveychatbotsession",
            name="chatbot_message",
            field=models.ForeignKey(
                blank=True,
                db_column="survey_chatbot_messages_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="survey.surveychatbotmessage",
                verbose_name="참조 메시지",
            ),
        ),
        migrations.DeleteModel(
            name="ChatbotMessage",
        ),
    ]
