# Generated by Django 6.0.4 on 2026-04-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0003_surveychatbotmessage_surveygamevector_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveychatbotsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "열림"),
                    ("in_progress", "진행 중"),
                    ("closed", "종료"),
                ],
                db_column="status",
                default="open",
                max_length=11,
                verbose_name="세션 상태",
            ),
        ),
    ]
