# Generated by Django 6.0.4 on 2026-04-21 08:47

import uuid

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0004_surveychatbotsession_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveychatbotsession",
            name="target_question_count",
            field=models.PositiveSmallIntegerField(
                blank=True,
                db_column="target_question_count",
                null=True,
                verbose_name="목표 질문 수",
            ),
        ),
        migrations.AlterField(
            model_name="surveychatbotsession",
            name="id",
            field=models.UUIDField(
                db_column="survey_chatbot_sessions_id",
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="surveygamevector",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, db_column="embedding", dimensions=1536, null=True
            ),
        ),
        migrations.AlterField(
            model_name="surveyrecommendgamelist",
            name="survey_game_vector",
            field=models.OneToOneField(
                db_column="survey_game_vector_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games",
                to="survey.surveygamevector",
            ),
        ),
        migrations.AlterField(
            model_name="surveyresults",
            name="chatbot_session",
            field=models.OneToOneField(
                blank=True,
                db_column="survey_chatbot_sessions_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="survey.surveychatbotsession",
            ),
        ),
        migrations.AddConstraint(
            model_name="surveychatbotmessage",
            constraint=models.UniqueConstraint(
                fields=("session", "sequence"),
                name="uq_survey_chatbot_messages_session_sequence",
            ),
        ),
    ]
