# Generated by Django 6.0.4 on 2026-04-24 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0005_surveychatbotsession_target_question_count_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="surveygamevector",
            name="game_list",
            field=models.BigIntegerField(
                blank=True, db_column="game_id", null=True, verbose_name="게임 ID"
            ),
        ),
        migrations.AddField(
            model_name="surveyresults",
            name="excluded_keywords",
            field=models.TextField(
                blank=True,
                db_column="excluded_keywords",
                null=True,
                verbose_name="추천 제외 키워드",
            ),
        ),
        migrations.AlterField(
            model_name="surveychatbotsession",
            name="user",
            field=models.OneToOneField(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="survey_chatbot_session",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.DeleteModel(
            name="SurveyRecommendGameList",
        ),
    ]
