# Generated by Django 6.0.4 on 2026-04-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0006_surveygamevector_game_list_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveygamevector",
            name="game_list",
            field=models.BigIntegerField(db_column="game_id", verbose_name="게임 ID"),
        ),
    ]
