# Generated by Django 6.0.4 on 2026-04-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0007_alter_surveygamevector_game_list"),
    ]

    operations = [
        migrations.RenameField(
            model_name="surveygamevector",
            old_name="game_list",
            new_name="game_id",
        ),
        migrations.AlterField(
            model_name="surveychatbotsession",
            name="using_model",
            field=models.CharField(
                blank=True,
                choices=[("GEMINI_2_5_FLASH", "Gemini 2.5 Flash")],
                db_column="using_model",
                max_length=50,
                null=True,
                verbose_name="사용 모델",
            ),
        ),
    ]
